In [ ]:
import pandas as pd

In [ ]:
pip install openai

Collecting openai
  Downloading openai-0.27.8-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.6/73.6 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.10/dist-packages (from openai) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from openai) (3.8.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (1.3.1)
Installing collected packages: openai
Successfully installed openai-0.27.8

In [ ]:
# API 키는 코드에 직접 적지 말고 환경 변수로 관리하세요
import os
from getpass import getpass

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY") or getpass("OpenAI API 키를 입력하세요: ")

# openai API 키 인증
openai.api_key = OPENAI_API_KEY

In [ ]:
import os

In [ ]:
path_dir = '/content/drive/MyDrive/새 폴더 (2)'

BB_file_list = os.listdir(path_dir)

path_dir = '/content/drive/MyDrive/새 폴더 (2)/'

SS_file_list = os.listdir(path_dir)

path_dir ="/content/drive/MyDrive/새 폴더 (2)/IT"
nnew_list = []
for i in range(len(SS_file_list)):
 nnew = path_dir + '/' + SS_file_list[i]
 nnew_list.append(nnew)

SS_file_list

In [ ]:
nnew_list = []
path_dir ="/content/drive/MyDrive/새 폴더 (2)/건"
SS_file_list = os.listdir(path_dir)
for Q in range(len(SS_file_list)):
   nnew = path_dir + '/' + SS_file_list[Q]
   nnew_list.append(nnew)

nnew_list

In [ ]:
search = "desktop.ini"
for word in nnew_list:
    if search in word:
        nnew_list.remove(word)
nnew_list

['/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_교육.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_마케팅시장조사.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_법률법무.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_엔지니어링.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_금융재무.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_전문직.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_기획경영.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_미디어홍보.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_은행금융_기획경영.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_유통무역.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_영업제휴.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_서비스고객지원.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_기타.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_생산제조.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_개발.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_생산관리품질관리.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_특수계층공공.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_데이터.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_연구개발.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_의약.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_인사총무.csv',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_디자인.csv']

In [ ]:
# 모델 - GPT 3.5 Turbo 선택
last_list= []
for i in nnew_list:
 with open(i, 'r',encoding='cp949') as f:
    k = f.read()

# 질문 작성하기
 query = '[k]의 내용으로 앞에 숫자 없이 면접느낌만 뺴줘'
# 메시지 설정하기
 messages = [
    {"role": "user", "content": query},
    {"role": "assistant", "content": k}
 ]

# ChatGPT API 호출하기
 response = openai.ChatCompletion.create(
    model= "gpt-3.5-turbo",
    messages=messages
)
 answer = response['choices'][0]['message']['content']
 last_list.append(i + answer)

In [ ]:
last_list

['/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_교육.csv1. 어떤 경험과 교육을 통해 본인이 이 직무에 적합한 능력을 갖추었다고 생각하시나요?\n2. 회사에 입사하면서 어떤 교육을 받았고, 이를 통해 어떤 전반적인 경험을 쌓았나요?\n3. 토목 분야에서 회사에 처음 입사하게 되면 어떤 부분을 가장 중요하게 생각하고, 어떤 인성 교육을 받았나요?\n4. 이전 직장에서의 실무 경험과 프로젝트를 통해 어떤 능력을 키웠나요? 회사에서 어떤 프로젝트에 참여하고 싶은지 말씀해주세요.\n5. 토목 분야의 기본 지식과 실무 경험으로부터 무엇을 배웠으며, 어떤 프로젝트 경험이 있나요?\n6. 프로젝트 관리 방법과 경력을 통해 어떻게 업무를 효과적으로 관리하고, 어떤 인성을 갖추고 계신지 말씀해주세요.\n7. 지금까지의 경력과 방법을 통해 어떻게 능력을 키웠고, 이를 직장에서 어떻게 활용할 수 있는지 설명해주세요.',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_마케팅시장조사.csv- 지원자는 마케팅 영역에서 어떤 경험을 가지고 계신가요? 회사에서 수행한 마케팅/시장조사 업무에 대해 설명해주세요.\n- 최근 경험한 회사에서의 업무는 어떤 내용이었나요? 그 업무를 통해 어떤 성과를 이뤄냈나요?\n- 이전 회사에서의 경력과 관련된 업무에서 인성적으로 어떤 측면을 발전시켰으며, 치열한 업무 환경에서 어떻게 대처했나요?\n- 관심 있는 직무에 지원한 이유는 무엇인가요? 마케팅 분야에서 어떤 경험을 바탕으로 재능을 발휘할 수 있다고 생각하시나요?\n- 이전 직장에서 퇴사하신 이유와 관련된 부동산 업무의 경험을 어떻게 적용할 수 있을지 설명해주세요.',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_법률법무.csv면접 질문입니다.\n\n1. 공무원 또는 기업에서의 준비과정에는 어떤 것들이 필요하나요?\n2. 나이가 있음에도 불구하고 어떻게 대처하시나요?\n3. 토론을 하는 과정에서 어떤 인성적인 요소가 중요하다고 생각하시나요?\n4. 토론의 기본적인 주제와 절차에 대해서 이야기해주세요.\n5. 최근 건설 업계에서 어떤 회사와 관련된 이슈가 있었는지 알고 계신가요?\n6. 회사에서 업무를 수행할 때 시간 관리는 어떻게 하시나요? \n7. 법률과 관련된 직무를 담당하는 회사에서 어떤 종류의 업무를 수행하였나요?\n8. 법률이나 법무에 관련된 직무에 대해 어떤 문제에 직면한 적이 있으며, 어떻게 해결하였나요?\n9. 현재 근무 중인 회사에서 법률과 관련된 직무를 어떻게 수행하고 계신가요?\n10. 현재 직무에 대해 개인적으로 어떤 측면을 더 공부하고 싶으신가요?\n11. 법률과 관련된 전공을 가지고 있으신데, 이를 어떻게 토지 관련 업무에 적용하실 수 있나요?\n12. 명령을 받았을 때, 다른 사람의 의견과 충돌하거나 수용하지 못할 때 어떻게 대처하시나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_엔지니어링.csv면접 질문:\n1. 어떤 회사에서 지원하셨나요?\n2. 엔지니어링 전공에 대한 기본적인 지식을 어떻게 습득하셨나요?\n3. 설계에 관심을 가지게 된 이유가 있나요? 취미로서 어떤 활동을 했나요?\n4. 이전에 공백기가 있었던 적이 있나요? 그동안에 특기를 개발하거나 졸업을 마치셨나요?\n5. 영어 능력이 있나요? 인성 있게 대처하는 능력도 중요합니다. 이러한 부분을 어떻게 준비하고 있나요?\n6. 자신의 직무인 엔지니어링과 관련된 건축, 시공, 가족 관계 등에 대해 어떤 경험이 있나요?\n7. 지금까지의 직무 경험 중 어떤 일을 가장 어려웠고, 어떻게 해결했나요? 관리와 현장 안전에 대해서도 언급해주세요.\n8. 현재 해외에서 업무를 수행 가능한지 여부가 궁금합니다. 업무 현장에 있을 수 있나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_금융재무.csv면접 질문:\n\n1. 회계 전공 직무에서 가장 중요한 인성은 무엇이라고 생각하십니까?\n2. 업무 경력에서 어떻게 관계를 유지하고 발전시키셨나요?\n3. 이전 회사에서 퇴사한 이유에 대해 설명해주세요.\n4. 이전 직장에서 어떤 업무를 맡았고 어떤 어려움을 극복했나요?\n5. 입사하려는 회사에서 예상되는 업무 스트레스에 대해 어떻게 대처하시겠습니까?\n6. 지금까지의 경험 중에서 가장 큰 성과가 무엇이었고, 어떻게 기여했나요?\n7. 회사에서 업무 압박을 받는 상황에 대처하는 방법은 무엇인가요?\n8. 회사에서 근무할 시간과 장소에 대해 어떤 제약이 있나요?\n9. 자신의 성격의 장단점은 무엇이며, 이를 업무에 어떻게 적용시킬 수 있나요?\n10. 이 회사에서 근무한 부서와 비슷한 업무를 하였을 때 어떤 상황에서 가장 잘 적응할 수 있을 것 같나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_전문직.csv1. 회사에 입사할 때 기본적으로 알아야 할 출근 및 업무 관련 규정은 무엇인가요?\n2. 전문직으로서 직무를 수행할 때 고려해야 할 마지막 기사 준비 상황은 어떤 것들이 있나요?\n3. 전문직으로 부동산 분야에서 개인 경력을 쌓을 때 어떤 답변과 경험이 중요한가요?\n4. 직무에서 압박감이 큰 안전 업무 현장에서의 역할은 어떻게 되는지 알려주세요.\n5. 전문직으로 근무하면서 영어 역량을 향상시키기 위해 어떤 방식으로 노력하셨나요?\n6. 전문직으로 근무하면서 회사 생활과 업무의 균형을 유지하는 방법은 무엇인가요?\n7. 전문직으로 근무하면서 회사 생활과 업무 역량 중 어떤 것에 더 중점을 둔 적이 있나요? 그 이유는 무엇인가요?\n8. 직장에서 자신의 경력을 관리하며 전문직으로 성장하기 위해 어떤 장단점을 고려해야 할까요?\n9. 전문직으로서 부동산 분야에서의 전공과 경험을 통해 관계를 구축하는데 어떤 방법이 효과적일까요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_기획경영.csv1. 영어 전공에 관련하여 어떤 경험이 있으신가요? 기획/경영 관련 개인적인 사례를 언급해주세요.\n2. 상사와의 토론 주제가 주어진 상황에서 어떤 자격증을 활용하여 해결책을 제시한 적이 있으신가요? 기획/경영의 관점에서 설명해주세요.\n3. 현재 진행 중인 사업에서 항만 공사 관련된 업무를 맡은 적이 있으신가요? 회사의 기획/경영적인 측면을 고려하는 방식에 대해서 이야기해주세요.\n4. 야근 가능 여부에 대해 어떻게 생각하시나요? 기획/경영 업무 관련 활동을 할 때 야근을 해야할 상황에 대한 자세한 의견을 말씀해주세요.\n5. 직무 수행 중 항만과 관련하여 어떤 인성적인 이야기가 있는지 알려주세요. 기획/경영 업무에서 어떤 방향으로 접근해야 하는지 소개해주세요.\n6. 회사에서 업무를 수행하는 동안 어떤 경험을 가지고 계셨나요? 특히 기획/경영 업무와 관련된 회사 상황을 해결한 경험에 대해 이야기해주세요.\n7. 현재 회사를 퇴사한 사유가 무엇인가요? 직장 관련 기획/경영적인 이유 중 퇴사 사유를 설명해주세요.\n8. 현재 진행 중인 프로젝트에서 개인적으로 업무를 어떻게 진행하고 있으신가요? 회사의 기획/경영 방향성에 맞게 업무를 효과적으로 진행하는 방법에 대해서 이야기해주세요.',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_미디어홍보.csv면접 질문:\n1. 경력이 없는 지원자에게 기본적인 업무 능력을 평가할 수 있는 방법이 있을까요? \n2. 최근의 광고 분위기에 대해 어떤 의견을 가지고 계신가요? \n3. 미디어/홍보 업무와 일반적인 홍보 업무의 차이점이 무엇인가요? \n4. 미디어/홍보 업무에서 개인적으로 강점과 단점을 어떻게 보여줄 수 있나요? \n5. 미디어/홍보 업무에서 결혼 및 퇴사와 같은 압박 상황을 어떻게 다루실 수 있나요? \n6. 아산 정책 연구원으로서의 경험과 경력에 대해 이야기해주세요. \n7. 이전 회사에서의 경험을 바탕으로 어떤 직장 환경이 가능하다고 느끼셨나요? \n8. 만약 성격이 다른 사람들과 일하는 상황에서 어떻게 대처하시나요? \n9. 미디어/홍보 업무에서 평가가 중요한 영어 능력과 관련하여 과거 어떤 경험을 가지고 계셨나요? \n10. 팀원들과의 협력과 주도적인 업무 수행 경험에 대해 이야기해주세요.',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_은행금융_기획경영.csv면접질문:\n1. 당신이 지원한 회사의 사업 내용을 아시나요?\n2. 인성과 성격에 대해서 어떻게 생각하시나요? \n3. 자신의 장점과 단점을 말씀해주세요. \n4. 이전 직장에서 어떤 업무를 담당했으며, 어떤 상황에서 문제를 해결했나요?\n5. 금융 및 보험 시장에 대해 어떤 경험이 있으신가요?\n6. 지원한 회사와 관련된 업무 경험이 있으신가요? 그런 경우에는 어떤 역할을 맡았고 성과는 어떻게 됐나요?\n7. 이전 직장에서 어떤 마지막 업무를 수행했으며, 일상 생활에서 어떤 활동을 주로 하시나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_유통무역.csv1. 유통/무역 업무에 대한 경험이 있으신가요?\n2. 이전 직장에서의 경력과 연봉에 대해 말씀해주세요.\n3. 이전 회사에서 어떤 자료를 다루었는지 알려주세요.\n4. 왜 이 회사에 지원하게 되었나요? 어떤 가능성을 보고 입사를 결정하셨나요? \n5. 서울에서 근무 가능하신가요? \n6. 이전 직장에서의 경험 중 어떤 부분이 특히 기억에 남았나요? \n7. 영업 전공으로 전환한 이유가 무엇인가요? 전공과 직무가 어떻게 연관되나요?\n8. 다른 회사에서의 프로젝트를 진행한 경험이 있으신가요? 어떤 프로젝트를 진행했는지 알려주세요.\n9. 입사 후에 해외 연락처와 협력해야하는 상황이 발생했을 때, 어떻게 대처하실 계획인가요?\n10. 현재 구매 업무를 수행하고 계시나요? 구매 업무에 대해 말씀해주세요.',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_영업제휴.csv1. 현재 가능한 회사 여부는 어디인가요? \n2. 이전 직장에서 어떤 업무를 담당하셨나요? \n3. 지금까지의 경력 사유는 어떻게 되나요? \n4. 건설 회사에서의 입사 경험을 어떻게 평가하시나요? \n5. 본인의 성격을 어떻게 설명하시나요? \n6. 영어를 사용하는 회사에서의 경력을 어떻게 진행하셨나요? \n7. 부동산과 관련된 사업에 대한 경험을 어떻게 갖고 계신가요? \n8. 전공으로 영어를 공부했는데, 그 전공을 활용하여 어떤 업무를 기억하나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_서비스고객지원.csv면접 질문:\n1. 해당 직무와 관련하여 어떤 경험이 가장 있으신가요?\n2. 이전 회사에서 담당하셨던 업무 중에서 어떤 문제가 있었고, 어떻게 해결하셨나요?\n3. 현재 담당하고 계신 업무를 얼마나 오래 수행하셨나요? 그리고 근무시간은 어떻게 되나요?\n4. 이 회사에 지원하게 된 동기는 무엇인가요? 이 회사의 사업에 대해서 어떤 기억이 있나요?\n5. 이전 근무 경력 중에서 특히 기억에 남는 회사가 있으신가요? 그 이유는 무엇인가요?\n6. 이전 업무나 프로젝트에서 마지막으로 어떤 경험을 가지셨나요? 그 직무와 관련하여 어떤 역할을 수행하였나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_기타.csv면접 질문:\n1. 기술과 관련된 회사 경력을 말해주세요. 어떤 문제를 해결했나요? 어떤 방식으로 해결했나요? \n2. 이 회사에 지원하기 위해 어떤 준비를 했나요? 주제를 선택하고 이에 대해 어떤 문제를 해결했나요? \n3. 인성과 관련하여 전공과 사람들과 어떤 토론을 나눠보았나요? 준비는 어떻게 하셨나요? \n4. 회사에서 쓰이는 공사 방식에 대해 알고 있나요? 어떤 주제에 대해 질문이 있으신가요? 어떤 답변을 준비하셨나요? \n5. 어디에서 일했는지 알려주세요. 어떤 준비를 했으며 어떤 자격증을 소유하고 있나요? 군대에서 근무한 경험이 있나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_생산제조.csv면접 질문:\n- 이 직무를 선택한 이유는 무엇인가요?\n- 이전 회사에서 어떤 경험을 쌓았나요? 그 경험으로부터 얻은 교훈이 있나요?\n- 해당 직무에 대한 자격증이 있나요? 만약 없다면, 어떻게 공부하거나 준비할 계획이 있나요?\n- 영어로 근무가 가능한 지역이 어디인지 나타낼 수 있나요? 영어 능력은 어느 정도인가요?\n- 이전 직장에서 가장 큰 성취를 이룬 경험이 있나요? 그 경험으로부터 배운 점은 무엇인가요?\n- 어떤 도전을 해보고 싶은지 말해보세요.\n- 어떤 문제를 해결해보았나요? 그 문제를 어떻게 해결했나요?\n- 왜 이 회사에 지원하려고 하나요? 해당 분야에서 전공한 이유가 있나요?\n- 전공과 관련된 프로젝트를 어떻게 진행했는지 설명해주세요.\n- 군대에서 어떤 자격증을 취득했나요? 군대 생활에서 어떤 점을 발전시킬 수 있을 것 같나요?\n- 이전 회사에서 인원 간에 갈등이 있었을 경우, 어떻게 대처했나요? 그 상황에서 배운 점은 무엇인가요?\n- 이 회사의 업무에 대해 더 알고 싶습니다. 이 업무를 경력으로 쌓고 싶은 이유가 있나요? 어떤 역량을 보유하고 있나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_개발.csv- 프로젝트 업무 경험 중 마지막 개발 프로젝트에 대해 어떤 업무를 수행했는지 알려주세요.\n- 프로젝트 개발이 중요한 이유와 그에 따른 장단점은 무엇인가요? \n- 기술 사유 경험을 바탕으로 업무에서 어떤 기술을 사용해 본 경험이 있는지 알려주세요. \n- 개발 직무 관련하여 가장 성과가 있는 과목이 무엇인가요? \n- 개발 프로젝트 경험에 대해 이야기하면서 회사에서 어떤 인성을 발휘했는지 알려주세요. \n- 이전 회사에서 프로젝트를 진행하면서 어떤 기술을 사용하였고, 어떻게 진행되었나요? \n- 개발 직무에 대한 실무 경력을 어떻게 쌓았고, 회사에서 어떤 기술을 발전시키고 싶은지 말씀해주세요. \n- 영어 사용이 가능한지와 관련하여 입사 과정에서 어떤 경험을 가지고 있는지 알려주세요.',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_생산관리품질관리.csv1. 당신이 회사에 입사하려는 포부가 무엇인가요? \n2. 지금까지 생산관리/품질관리 분야에서 어떤 경험을 가지고 계신가요? \n3. 회사에서의 당신의 역할은 어떤 것이었나요? \n4. 근무하고자 하는 현장이 어떤 조건에서 가능한가요? \n5. 이전 직장에서의 생산관리/품질관리 경력을 기억하고 있는 특별한 사례가 있나요? \n6. 생산관리/품질관리 직무를 수행하는 방법에 대해 어떻게 생각하나요? \n7. 현장에서 발생하는 문제를 해결하는데 어떤 경험이 있나요? \n8. 안전 관리에 대한 회사의 성격을 어떻게 평가하시나요? \n9. 영어 능력을 활용하여 생산관리/품질관리 업무를 수행한 경험이 있나요? \n10. 어떤 지방에서 근무 가능한지 알려주세요.',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_특수계층공공.csv면접 질문:\n0. 특수 계층 또는 공공 관련 경험이 없으시다면, 사업, 자격증, 경험 등에서 어떤 강점을 가지고 계신가요?\n1. 특수 계층이나 공공 기관에서 업무를 수행하다가 생기는 갈등 상황을 어떻게 대처하시는지 알려주세요.\n2. 특수 계층이나 공공 기관에서 근무하며 어떤 종류의 사람들과 일해보셨나요? 이 경험이 어떻게 도움이 되었나요?\n3. 특수 계층이나 공공 기관에서 근무하면서 어떤 종류의 민원 상황을 다뤄보셨나요? 어떤 인성적인 특징을 가지고 있었나요?\n4. 특수 계층이나 공공 기관에서 업무를 수행하면서 부서나 사업을 어떻게 관리하셨나요? 도시 관리와 관련하여 어떤 경험이 있으신지 말씀해주세요.\n5. 특수 계층이나 공공 기관과 관련하여 어떤 경험을 가지고 계신지 알려주세요. 이 회사에 입사하게 된다면 어떤 업무를 수행하고 싶으신가요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_데이터.csv면접 질문:\n1. 평소에 데이터와 관련된 업무에 대해 어떤 포부나 열망을 가지고 계셨나요?\n2. 이전에 진행한 프로젝트 중 데이터와 관련된 업무 경험이 있으신가요? 해당 프로젝트의 내용에 대해 설명해주세요.\n3. 어떤 경험을 통해 데이터와 관련된 업무의 분위기에 적응하고 잘 활용할 수 있는 역량을 갖추게 되었나요?\n4. 이전에 참여한 프로젝트에서 데이터를 사용하고 수직적인 분위기를 조성하는 일이 있었을까요? 그 경험에 대해 설명해주세요.\n5. 회사 내에서 수직적인 분위기 속에서 데이터와 관련된 프로젝트 경험이 있다면 어떤 내용이었나요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_연구개발.csv0. 회사에서의 분자 기억 연구개발 업무에 대해 어떤 경험이 있으신가요?\n1. 피티 직장에서의 전공과 인성적인 측면에서 어떤 역할을 담당했나요?\n2. 입사하고 나서 해외에서의 직무 근무를 어떻게 계획하고 계시나요?\n3. 다른 회사에서 실무 경험을 쌓은 이유와 분자 기억 연구개발 분야 이외의 부동산 회사와의 관련성에 대해 설명해주세요.\n4. 연구개발 분야에서의 경력을 바탕으로 개인적으로 기여한 경험이 가장 중요한 역할을 한 적이 있나요?\n5. 지금까지 진행한 연구개발 주제 중에서 공사와 개별적인 경험이 있는 주제가 있으신가요?\n6. 회사에서의 영어 업무에 대비해 어떤 준비와 지방에서의 근무에 어떻게 대응하실 생각인가요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_의약.csv1. 결혼 후에도 근무가 가능한가요?\n2. 업무 현장에서 사람들과의 관계를 잘해낼 수 있는가요?\n3. 의약 분야에 대한 지식이 있나요?\n4. 근무 가능한 시간과 기간이 있나요?\n5. 건설 업무에 대한 경험이 있나요?\n6. 문제 해결능력이 뛰어난 편인가요?\n7. 지금까지 업무 관련 회사에 다니신 적이 있나요?\n8. 퇴사 경험이 있으신가요?\n9. 직무에 필요한 업무에 대한 전문 지식이 있나요?\n10. 업무 현장에서 사람들과 잘 어울릴 수 있는 성격인가요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_인사총무.csv면접 질문:\n1. 경험을 통해 어떤 업무를 해결한 경험이 있나요?\n2. 인사/총무 업무에 관련된 경험을 어떻게 쌓아오셨나요?\n3. 회사에 출근하는 시간과 연봉 조건에 대해 어떻게 생각하시나요?\n4. 지원한 직무에 관련된 인성과 업무 능력을 어떻게 평가하시나요?\n5. 지금까지 근무한 회사들과 업무 경력, 성격에 대해 자세히 알려주세요.\n6. 인사 업무에서의 경험과 직장 내 인사 관련 업무에 대해 어떤 경험을 가지고 계신가요?',
 '/content/drive/MyDrive/새 폴더 (2)/건/LDA_건설 (1)_디자인.csv면접 질문:\n1. 디자인 직무를 위해 어떤 경험이 있으신가요? 이전 회사에서 어떤 프로젝트를 수행했나요?\n2. 회사에 지원한 이유와 디자인 분야에서 어떤 프로젝트를 하고 싶으신가요? 포트폴리오에 어떤 작업물이 있나요?\n3. 야근과 같은 힘들거나 스트레스를 받는 상황에서 어떻게 대처하시나요? 이전 회사에서 어떤 야근 경험이 있었나요?\n4. 회사에 입사하면서 어떤 성격의 사람은 적합하지 않을 것 같다고 생각하시나요? 포트폴리오를 기반으로 설명해주세요.\n5. 결혼이나 가정 생활과 업무를 어떻게 조화롭게 이어나갈 계획이 있으신가요? 야근을 해야하는 상황이 생긴다면 어떻게 대처하실 건가요?\n6. 이전 프로젝트 중에서 인상 깊게 남은 작품이 있나요? 그 작품을 만들면서 어떤 업무와 야근이 있었나요? 임원이 어떤 피드백을 주셨나요?\n7. 실기 시험에서는 어떤 내용을 준비하셨나요? 포트폴리오를 통해 보여줄 수 없는 기술을 어떻게 평가받고 싶으신가요? 시험 진행 중 어떤 어려움이 있었나요?\n8. 설계 분야는 어떤 분야에서 주로 활동하려고 생각하시나요? 포트폴리오에 있는 인테리어 디자인 작업물 중에서 가장 자신 있는 작업물은 무엇인가요?\n9. 회사에서는 어떻게 당신의 경력을 평가하고 계획하며, 인사 시스템과 관련하여 어떤 연봉기준이 적용되는지 알고 있으신가요? 디자인 직무에서 기본적으로 기대되는 업무 능력은 어떤 것인가요?']

In [ ]:
df2 = pd.read_csv('/content/미분할.csv')

In [ ]:
df1 = pd.read_csv('/content/미분할.csv')

In [ ]:
df3 = pd.read_csv('/content/분할.csv')

In [ ]:
df3

,first_word,job_title,split_content
0,제조,영업제휴,회사 내에서 영어와 외국어를 사용한 경력이 있으신가요
1,제조,영업제휴,\n 영업제휴 직무에 어떤 기본적인 역량을 보유하고 계신가요
2,제조,영업제휴,\n 면접을 위해 인성면접을 진행했던 경험이 있으신가요
3,제조,영업제휴,준비는 어떻게 하셨나요
4,제조,영업제휴,\n 영업제휴 직무에 토론 능력이 중요하다고 생각하시나요
...,...,...,...
2065,건설,엔지니어링,토론 주제를 진행하고 발표하는 과정에서 어떤 기술을 사용하셨나요
2066,건설,엔지니어링,이전 업무 경력에서 이직한 이유와 관련하여 어떤 사유로 이직하신 건가요
2067,건설,엔지니어링,업무 관리에서 문제를 해결하기 위해 어떤 방법을 사용하셨나요
2068,건설,엔지니어링,현장에서의 안전 관리에 대해서 어떤 고려사항을 가지고 계신가요
2069,건설,엔지니어링,근무 가능한 현장에 대해 어떤 조건을 고려하시고 해외에서의 근무 여부에 대해서 어...

In [ ]:
df123 = pd.read_csv('/content/constructed_dataframe.csv')

In [ ]:
df123

,Column1,Column2,Column3
0,건,교육,1. 어떤 경험과 교육을 통해 본인이 이 직무에 적합한 능력을 갖추었다고 생각하시나...
1,건,마케팅시장조사,- 지원자는 마케팅 영역에서 어떤 경험을 가지고 계신가요? 회사에서 수행한 마케팅/...
2,건,법률법무,면접 질문입니다.\n\n1. 공무원 또는 기업에서의 준비과정에는 어떤 것들이 필요하...
3,건,엔지니어링,면접 질문:\n1. 어떤 회사에서 지원하셨나요?\n2. 엔지니어링 전공에 대한 기본...
4,건,금융재무,면접 질문:\n\n1. 회계 전공 직무에서 가장 중요한 인성은 무엇이라고 생각하십니...
5,건,전문직,1. 회사에 입사할 때 기본적으로 알아야 할 출근 및 업무 관련 규정은 무엇인가요?...
6,건,기획경영,1. 영어 전공에 관련하여 어떤 경험이 있으신가요? 기획/경영 관련 개인적인 사례를...
7,건,미디어홍보,면접 질문:\n1. 경력이 없는 지원자에게 기본적인 업무 능력을 평가할 수 있는 방...
8,건,유통무역,1. 유통/무역 업무에 대한 경험이 있으신가요?\n2. 이전 직장에서의 경력과 연봉...
9,건,영업제휴,1. 현재 가능한 회사 여부는 어디인가요? \n2. 이전 직장에서 어떤 업무를 담당...
10,건,서비스고객지원,면접 질문:\n1. 해당 직무와 관련하여 어떤 경험이 가장 있으신가요?\n2. 이전...
11,건,기타,면접 질문:\n1. 기술과 관련된 회사 경력을 말해주세요. 어떤 문제를 해결했나요?...
12,건,생산제조,면접 질문:\n- 이 직무를 선택한 이유는 무엇인가요?\n- 이전 회사에서 어떤 경...
13,건,개발,- 프로젝트 업무 경험 중 마지막 개발 프로젝트에 대해 어떤 업무를 수행했는지 알려...
14,건,생산관리품질관리,1. 당신이 회사에 입사하려는 포부가 무엇인가요? \n2. 지금까지 생산관리/품질관...
15,건,특수계층공공,"면접 질문:\n0. 특수 계층 또는 공공 관련 경험이 없으시다면, 사업, 자격증, ..."
16,건,데이터,면접 질문:\n1. 평소에 데이터와 관련된 업무에 대해 어떤 포부나 열망을 가지고 ...
17,건,연구개발,0. 회사에서의 분자 기억 연구개발 업무에 대해 어떤 경험이 있으신가요?\n1. 피...
18,건,의약,1. 결혼 후에도 근무가 가능한가요?\n2. 업무 현장에서 사람들과의 관계를 잘해낼...
19,건,인사총무,면접 질문:\n1. 경험을 통해 어떤 업무를 해결한 경험이 있나요?\n2. 인사/총...
20,건,디자인,면접 질문:\n1. 디자인 직무를 위해 어떤 경험이 있으신가요? 이전 회사에서 어떤...

In [ ]:
with open("wwww.txt", "w") as file:
    for item in last_list:
        file.write("%s\n" % item)

In [ ]:
with open('산업','w',encoding = 'UTF-8') as f:
 for name in k:
  f.write(name+'\n')

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
con = sqlite3.connect("/content/question.db")

In [ ]:
df2.to_sql('질문 미분할', con)

In [ ]:
df3.to_sql('질문 분할', con)